/* tslint:disable:object-literal-key-quotes */

export const googleSheetsAPIMockResponseData = {
  range: 'Characters!A1:L7',
  majorDimension: 'ROWS',
  values: [
    [
      'Active',
      'ID',
      'Name',
      'Email Address',
      'Contact Street',
      'Contact Street Number',
      'Contact ZIP',
      'Contact City',
      'Skill 1',
      'Skill 2',
      'Skill 3',
      'irrelevant column',
    ],
    [
      'no',
      '1',
      'Lisa',
      'lisa.s@test.com',
      'Evergreen Terrace',
      '742',
      '58008',
      'Springfield',
      'saxophone',
      'art',
      'science',
      'this',
    ],
    [
      'yes',
      '2',
      'Marge',
      '',
      'Evergreen Terrace',
      '742',
      '58008',
      'Springfield',
      'painting',
      'bowling',
      '',
      'should',
    ],
    [
      'no',
      '3',
      'Homer',
      '',
      'Evergreen Terrace',
      '742',
      '58008',
      'Springfield',
      'beer',
      'donuts',
      '',
      'not',
    ],
    [
      'yes',
      '4',
      'Bart',
      'el.barto@smail.com',
      'Evergreen Terrace',
      '742',
      '58008',
      'Springfield',
      'eat my shorts',
      'skateboarding',
      '',
      'be',
    ],
    [
      'yes',
      '5',
      'Ralph',
      'ralphie@test-mail.com',
      'Main Street',
      '1234',
      '58008',
      'Springfield',
      '',
      '',
      '',
      'visible',
    ],
  ],
};
