name: Test, Lint, Build and Deploy

on:
  push:
  release:
    types:
      - published

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: make install

  lib_test_and_lint:
    name: Test and Lint library
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: make test-lib-ci
    - run: make lint-lib

  lib_publish:
    name: Publish library
    needs: setup
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: make publish-lib
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  demo:
    name: Build, test, lint and deploy demo application
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: make build-lib
    - run: make test-demo-ci
    - run: make lint-demo
    - run: make deploy-demo
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
